version: '3.8'

services:
  mongodb:
    container_name: turkcell2-filterdb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "turkcell"
      MONGO_INITDB_ROOT_PASSWORD: "12345"
    volumes:
      - "/data/db/"