version: '3.8'

services:
  kafka:
    container_name: kafka-t2
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.102:9092

  mongodb:
    container_name: turkcell2-filterdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  inventorydb:
    container_name: inventorydb-t2
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_TCP_PORT=3306
      - VIRTUAL_PORT=3306
    volumes:
      - inventorydb:/data/db

volumes:
  kafka_data:
  mongodb_data:
  inventorydb: