spring:
  datasource:
    username: postgres
    password: '12345'
    url: jdbc:postgresql://localhost:5432/inventorydb-t2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
